name: PHP Code Sniffer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
    - uses: actions/checkout@v4

    

    - name: Set up PHP with necessary extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'  # Defina a versão correta do PHP, se necessário
        extensions: sockets, pdo_pgsql

    - name: Install dependencies with Composer
      run: composer install

    - name: PHPCS
      run: composer run phpcs

